export const VALID_ROLES = ['ADMIN', 'PRICING_LEAD', 'UNDERWRITER', 'SALES_HEAD', 'SALES_EXEC'] as const;

export type Role = typeof VALID_ROLES[number];

export const ALLOWED_STATUS_CHANGES: Record<Role, string[]> = {
  ADMIN: ['DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'NEGOTIATION', 'APPROVED', 'REJECTED', 'EXPIRED'],
  PRICING_LEAD: ['DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'NEGOTIATION', 'APPROVED', 'REJECTED', 'EXPIRED'],
  UNDERWRITER: ['UNDER_REVIEW', 'APPROVED', 'REJECTED'],
  SALES_HEAD: ['DRAFT', 'SUBMITTED'],
  SALES_EXEC: ['DRAFT', 'SUBMITTED']
};

export const JWT_EXPIRY = '12h';
